- name: Load CSV file {{ firewall_address_csv_file | basename() }}
  community.general.read_csv:
    path: '{{ firewall_address_csv_file }}'
    fieldnames: name,subnet,color
    delimiter: ','
  register: firewall_addresses
  delegate_to: localhost
  tags: create_objects
  
- name: Upload Firewall Addresses
  fmgr_firewall_address:
    adom: '{{ adom_name }}'
    state: present
    firewall_address:
      name: '{{ item.name }}'
      subnet: '{{ item.subnet }}'
      color: '{{ item.color }}'
      comment: "{{ description }}"
  loop: '{{ firewall_addresses.list }}'
  tags: create_objects