- name: Organize Devices Groups in {{ adom_name }}/{{  device_group.name }}
  fmgr_generic:
    method: add
    params:
      - url: /dvmdb/adom/{{ adom_name }}/group/{{ device_group.name }}/object member
        data:
          - name: '{{ device_group_member }}'
            #vdom: root
  loop: '{{ device_group.members }}'
  loop_control:
    loop_var: device_group_member
  tags: organize_device_groups            