- name: Set Installation Targets for Policy Package {{ adom_name }}{{ policy_package_target.name }}
  fmgr_generic:
    method: set
    params:
      - url: pm/pkg/adom/{{ adom_name }}{{ policy_package_target.name }}
        data:
          scope member:
            - name: "{{ policy_package_target.target }}"  
              vdom: root
  tags: set_policy_package_targets